name: Mirror Linux Kernel

on:
  # Löst den Workflow manuell über die GitHub Actions UI aus
  workflow_dispatch:

  # Löst den Workflow einmal täglich um 03:00 UTC aus
  schedule:
    - cron: '0 3 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout existing mirror repository
        uses: actions/checkout@v4
        with:
          # Wir benötigen die vollen Git-Historie, um korrekt zu spiegeln
          fetch-depth: 0
          # Dein persönliches GitHub Token, um Push-Rechte zu haben
          token: ${{ secrets.GH_TOKEN }}

      - name: Add kernel.org remote
        run: |
          git remote add kernel-org https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
        # Überprüfe, ob das Remote bereits existiert, um Fehler bei wiederholten Läufen zu vermeiden
        # (optional, git remote add sollte intelligent genug sein)
          git remote set-url kernel-org https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git

      - name: Fetch from kernel.org
        run: |
          # Führe einen "bare" Fetch aus, um alle Referenzen von kernel.org zu bekommen
          # Verwende --tags und --force, um sicherzustellen, dass alle Tags und Branches aktualisiert werden
          echo "Fetching latest changes from kernel.org..."
          git fetch kernel-org --tags --force --prune || { echo "Failed to fetch from kernel.org"; exit 1; }

      - name: Mirror branches and tags
        run: |
          echo "Mirroring branches..."
          for branch in $(git branch -r | grep kernel-org/ | sed 's/kernel-org\///' | grep -v HEAD); do
            git push origin "kernel-org/${branch}:${branch}" || { echo "Failed to push branch ${branch}"; }
          done

          echo "Mirroring tags..."
          git push origin --tags || { echo "Failed to push tags"; }

        env:
          # Optional: Wenn du spezielle Git-Konfigurationen brauchst
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

      - name: Clean up remote
        # Entfernt das kernel-org Remote nach dem Spiegeln
        run: |
          git remote remove kernel-org
        continue-on-error: true # Setze dies auf true, damit der Workflow nicht fehlschlägt, falls das Remote nicht existiert
