name: Mirror Linux Kernel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Ensure kernel.org remote exists
        run: |
          if git remote | grep -q kernel-org; then
            git remote set-url kernel-org https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
          else
            git remote add kernel-org https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
          fi

      - name: Fetch from kernel.org
        run: |
          echo "Fetching latest changes from kernel.org..."
          git fetch kernel-org --tags --force --prune || { echo "Failed to fetch from kernel.org"; exit 1; }

      - name: Mirror branches
        run: |
          echo "Mirroring branches..."
          for branch in $(git branch -r | grep kernel-org/ | sed 's/kernel-org\///' | grep -v HEAD); do
            git push origin "kernel-org/${branch}:${branch}" || echo "Failed to push branch ${branch}"
          done

      - name: Mirror tags
        run: |
          echo "Mirroring tags..."
          git push origin --tags || echo "Failed to push tags"

      - name: Clean up kernel.org remote
        run: |
          git remote remove kernel-org || true
        continue-on-error: true
